services:
  db:
    image: postgres:16-alpine
    container_name: nerovia-db-dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: nerovia
      POSTGRES_USER: nerovia
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data

volumes:
  postgres_dev_data:
